---
- name: Include sysctl variables
  ansible.builtin.include_vars: sysctl.yml

- name: Create rc.local
  ansible.builtin.template:
    src: rc.local
    dest: /etc/rc.local

- name: Set permissions for rc.local
  ansible.builtin.file:
    path: /etc/rc.local
    owner: root
    group: root
    mode: "0755"

- name: Re-run rc.local to bind IPs
  ansible.builtin.command:
    cmd: /etc/rc.local
  ignore_errors: yes

- name: Update sysctl
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_conf }}'
